### PR TITLE
Update readme and .lib

### PR DESCRIPTION
**Pull request by rajkan01**
- Updated readme with renamed example name and .lib to refer new renamed client repo

### CODE REVIEW

**Review by LDong-Arm — COMMENTED** [review]
The target branch needs to be "development"

**Review by LDong-Arm — COMMENTED** [review]
Good opportunity to also update the README title to "Mbed OS example for AWS IoT SDK" (or something better if you can think of one)

**Review by LDong-Arm — APPROVED** [review]

**Review by evedon — APPROVED** [review]

**Review by evedon — CHANGES_REQUESTED** [review]
Please update .circleci/config.yml as well

**Comment by LDong-Arm** [comment]
This PR has a commit "Merge pull request #16 from ARMmbed/development" which is on master instead of development. Maybe this PR can be rebased onto development so we can get rid of that commit, but it's not a big problem though.

**Review by evedon — APPROVED** [review]

**Pull request merged**
